"""initial schema

Revision ID: f4f1a3b74a3f
Revises: 
Create Date: 2026-08-23 16:11:57.364391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = 'f4f1a3b74a3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('from_agent', sa.Enum('SCOUT', 'ANALYST', 'AUDITOR', 'MITIGATOR', 'ORCHESTRATOR', name='agent_role'), nullable=False),
    sa.Column('to_agent', sa.Enum('SCOUT', 'ANALYST', 'AUDITOR', 'MITIGATOR', 'ORCHESTRATOR', name='agent_role_to'), nullable=True),
    sa.Column('message_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', sqlite.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index('ix_agent_message_workflow_timestamp', ['workflow_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('cost_tracking',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('cost_metadata', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_tracking', schema=None) as batch_op:
        batch_op.create_index('ix_cost_supplier_created', ['supplier_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_tracking_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_tracking_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_tracking_workflow_id'), ['workflow_id'], unique=False)
        batch_op.create_index('ix_cost_workflow_created', ['workflow_id', 'created_at'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'UNKNOWN', name='supplier_tier'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('last_assessed', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('supplier_metadata', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('ix_supplier_country_industry', ['country', 'industry'], unique=False)
        batch_op.create_index('ix_supplier_tier_active', ['tier', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_type', sa.Enum('AUTONOMOUS_DISCOVERY', 'DEEP_DIVE_INVESTIGATION', 'COMPLIANCE_CHECK', 'ALTERNATIVE_SOURCING', name='workflow_type'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('investigation_result', sqlite.JSON(), nullable=False),
    sa.Column('hitl_required', sa.Boolean(), nullable=False),
    sa.Column('hitl_status', sa.String(length=50), nullable=True),
    sa.Column('hitl_payload', sqlite.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index('ix_investigation_supplier_status', ['supplier_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_workflow_id'), ['workflow_id'], unique=True)

    op.create_table('alternative_suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_supplier_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('cost_difference_pct', sa.Float(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('quality_rating', sa.Float(), nullable=True),
    sa.Column('certifications', sqlite.JSON(), nullable=False),
    sa.Column('alt_metadata', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alternative_suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alternative_suppliers_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alternative_suppliers_original_supplier_id'), ['original_supplier_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('NEWS_ARTICLE', 'FINANCIAL_REPORT', 'SANCTIONS_LIST', 'SATELLITE_IMAGERY', 'GOVERNMENT_REGISTRY', 'SUPPLIER_COMMUNICATION', 'SOCIAL_MEDIA', 'INTERNAL_DOCUMENT', name='evidence_type'), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('evidence_metadata', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index('ix_evidence_published_at', ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index('ix_evidence_supplier_type', ['supplier_id', 'type'], unique=False)

    op.create_table('risk_factors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('GEOPOLITICAL', 'FINANCIAL', 'ESG', 'REGULATORY', 'OPERATIONAL', 'CYBER', 'NATURAL_DISASTER', 'SUPPLIER_VIABILITY', name='risk_category'), nullable=False),
    sa.Column('level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'SEVERE', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sqlite.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('likelihood_score', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('risk_metadata', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_factors', schema=None) as batch_op:
        batch_op.create_index('ix_risk_factor_level', ['level'], unique=False)
        batch_op.create_index('ix_risk_factor_supplier_category', ['supplier_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_factors_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_factors_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('mitigation_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('risk_factor_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('estimated_timeline_days', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('action_metadata', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_factor_id'], ['risk_factors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mitigation_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mitigation_actions_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mitigation_actions_risk_factor_id'), ['risk_factor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mitigation_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mitigation_actions_risk_factor_id'))
        batch_op.drop_index(batch_op.f('ix_mitigation_actions_investigation_id'))

    op.drop_table('mitigation_actions')
    with op.batch_alter_table('risk_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_factors_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_risk_factors_investigation_id'))
        batch_op.drop_index('ix_risk_factor_supplier_category')
        batch_op.drop_index('ix_risk_factor_level')

    op.drop_table('risk_factors')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_supplier_type')
        batch_op.drop_index(batch_op.f('ix_evidence_supplier_id'))
        batch_op.drop_index('ix_evidence_published_at')
        batch_op.drop_index(batch_op.f('ix_evidence_investigation_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('alternative_suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alternative_suppliers_original_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_alternative_suppliers_investigation_id'))

    op.drop_table('alternative_suppliers')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_investigations_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_investigations_status'))
        batch_op.drop_index('ix_investigation_supplier_status')

    op.drop_table('investigations')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))
        batch_op.drop_index(batch_op.f('ix_suppliers_industry'))
        batch_op.drop_index(batch_op.f('ix_suppliers_country'))
        batch_op.drop_index('ix_supplier_tier_active')
        batch_op.drop_index('ix_supplier_country_industry')

    op.drop_table('suppliers')
    with op.batch_alter_table('cost_tracking', schema=None) as batch_op:
        batch_op.drop_index('ix_cost_workflow_created')
        batch_op.drop_index(batch_op.f('ix_cost_tracking_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_cost_tracking_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_cost_tracking_created_at'))
        batch_op.drop_index('ix_cost_supplier_created')

    op.drop_table('cost_tracking')
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_messages_workflow_id'))
        batch_op.drop_index('ix_agent_message_workflow_timestamp')

    op.drop_table('agent_messages')
    # ### end Alembic commands ###
